.\"                                      Hey, EMACS: -*- nroff -*-
.\" xqf.6 is copyright 1999-2001 by Jordi Mallach <jordi@debian.org>
.\" 
.\" This is free documentation, see the latest version of the GNU
.\" General Public License for copying conditions. There is NO warranty.
.TH XQF 6 "December 19, 2004"
.SH NAME
xqf \- 3D action game server browser
.SH SYNOPSIS
.B xqf
.RI [ options ]
.SH DESCRIPTION
\fBXQF\fP is a 3D action game (such as Quake, sequels and derivatives) server
browser. It uses X and is written using the GIMP Tool Kit, and uses QStat in
the backend to retrieve server info.
.PP
With XQF you can search for Quake, Quake World, Quake2, Quake3, Return to 
Castle Wolfenstein, Hexen 2, Hexen World, Sin, Half-Life, Kingpin, 
Soldier of Fortun 1/2, Tribes 2, Heretic 2, Unreal, Unreal Tournament, 
Unreal Tournament 2003, Rune, Descent 3 and many others. You can look at lots
of information about the servers. XQF can spawn your client into a selected
server with customized options. You can also apply filters while searching for
servers, trimming full or empty servers, for example.
.SH OPTIONS
 XQF accepts several command line parameters:
.TP
.BI \-\-launch " [SERVERTYPE] IP"
adds the server specified with IP (e.g. 10.10.0.1:27666) to the favorites,
queries it and launches the game. XQF tries to automatically determine the
correct game based on the port. If the autodetections fails XQF will ask you
for the game. Alternatively you may directly specify the game type on the
command line (e.g. Q3S).
.TP
.BI \-\-add " [SERVERTYPE] IP"
adds the specified server to the favories and queries it. Basically the same as
\-\-launch except that the game is not launched ;-)
.TP
.BI \-\-debug " level"
set the specified debug level. Use this if you experience problems with XQF.
Level 3 is usually sufficient for debugging most problems. Higher levels
product lots of output.
.TP
.B \-\-version
prints the version of XQF.
.SH SEE ALSO
.BR qstat(1).
.TP
.I /usr/share/doc/xqf
.SH HOMEPAGE
http://linuxgames.com/xqf/
http://www.sourceforge.net/projects/xqf/
.SH AUTHOR
This manual page was written by Jordi Mallach <jordi@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.br
XQF was written by Roman Pozlevich <roma@botik.ru>, and is now maintained
by Bill Adams <bill@evilbill.org>, Alex Burger <alex_b@users.sourceforge.net>
and Ludwig Nussel <l_n@users.sourceforge.net>
