name: Build
on: [push, pull_request]

jobs:
  linux-gcc:
    name: GCC (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y qstat intltool cmake libgtk2.0-dev libgeoip-dev libminizip-dev
    - name: cmake
      run: CC=gcc CXX=g++ cmake -DWITH_QSTAT=/usr/bin/quakestat -DCMAKE_C_FLAGS=-Werror .
    - name: make
      run: make
    - name: make install
      run: sudo make install

  linux-clang:
    name: Clang (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y qstat intltool cmake libgtk2.0-dev libgeoip-dev libminizip-dev
    - name: cmake
      run: CC=clang CXX=clang++ cmake -DWITH_QSTAT=/usr/bin/quakestat -DCMAKE_C_FLAGS=-Werror .
    - name: make
      run: make
    - name: make install
      run: sudo make install
